name: semantic-release
run-name: Semantic Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read           # for checkout

jobs:
  test-echo:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        env:
          MESSAGE: ${{ github.event_name }}
        run: echo $MESSAGE

  release:
    name: Release
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write      # to be able to publish a GitHub release
      issues: write        # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write      # to enable use of OIDC for npm provenance
    steps:
      - name: Debug
        env:
          MESSAGE: ${{ github.event_name }}
        run: echo $MESSAGE

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install @semantic-release/changelog -D

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
