name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_call:
    inputs:
      caller:
        description: 'Workflow caller'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      caller:
        description: 'Workflow caller'
        default: 'manual'
        required: false
        type: string

jobs:
  echo-caller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print the caller to STDOUT
        run: "echo The caller is ${{ inputs.caller }}"
